/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-OPC.h
 #	source generated by 4D Plugin Wizard
 #	Project : OPC
 #	author : miyako
 #	2020/05/08
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_OPC_H
#define PLUGIN_OPC_H

#include "4DPluginAPI.h"

#include "ARRAY_TEXT.h"
#include "C_TEXT.h"
#include "C_BLOB.h"
#include "C_LONGINT.h"

#include <opc/opc.h>

#include <sstream>

#pragma mark -

void OPC_Get_document_type(PA_PluginParameters params);
void OPC_RESOURCE_TYPE_LIST(PA_PluginParameters params);
void OPC_EXTERNAL_TARGET_LIST(PA_PluginParameters params);
void OPC_EXTENSION_LIST(PA_PluginParameters params);
void OPC_Register_resource_type(PA_PluginParameters params);
void OPC_RELATION_TYPE_LIST(PA_PluginParameters params);
void OPC_Get_resource(PA_PluginParameters params);
void OPC_RESOURCE_LIST(PA_PluginParameters params);
void OPC_Get_resource_size(PA_PluginParameters params);
void OPC_Delete_resource(PA_PluginParameters params);
void OPC_Set_resource(PA_PluginParameters params);
void OPC_EXTERNAL_RESOURCE_LIST(PA_PluginParameters params);
void OPC_Create_relation(PA_PluginParameters params);
void OPC_Remove_relation(PA_PluginParameters params);
void OPC_Create_external_relation(PA_PluginParameters params);
void OPC_RELATION_LIST(PA_PluginParameters params);
void OPC_Document_type(PA_PluginParameters params);
void OPC_Relation_type(PA_PluginParameters params);

typedef enum {
    
    OPC_DOCX = 0,
    OPC_XLSX,
    OPC_PPTX
    
}OPC_DOC_TYPE;

typedef enum {
    
    OPC_IMAGE = 0,
    OPC_STYLES,
    OPC_STYLES_WITH_EFFECTS,
    OPC_SETTINGS,
    OPC_WEB_SETTINGS,
    OPC_FONT_TABLE,
    OPC_THEME
    
}OPC_RELATION_TYPE;

#define OPC_ERROR_INVALID_PATH -1
#define OPC_ERROR_INVALID_RESOURCE_ID -2
#define OPC_ERROR_INVALID_RELATION_ID -3
#define OPC_ERROR_INVALID_RELATION_TYPE -4

#define DEFAULT_RELATION_PREFIX (const uint8_t *)"rId"

#define OPC_DOCX_TYPE (const uint8_t *)"application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"
#define OPC_XLSX_TYPE (const uint8_t *)"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"
#define OPC_PPTX_TYPE (const uint8_t *)"application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"

#define OPC_IMAGE_RELATION (const uint8_t *)"http://schemas.openxmlformats.org/officeDocument/2006/relationships/image"
#define OPC_THEME_RELATION (const uint8_t *)"http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme"
#define OPC_FONT_TABLE_RELATION (const uint8_t *)"http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable"
#define OPC_STYLES_RELATION (const uint8_t *)"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles"
#define OPC_STYLES_WITH_EFFECTS_RELATION (const uint8_t *)"http://schemas.microsoft.com/office/2007/relationships/stylesWithEffects"
#define OPC_SETTINGS_RELATION (const uint8_t *)"http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings"
#define OPC_WEB_SETTINGS_RELATION (const uint8_t *)"http://schemas.openxmlformats.org/officeDocument/2006/relationships/webSettings"

#define OPC_DOCX_TYPE_LEN 80
#define OPC_XLSX_TYPE_LEN 74
#define OPC_PPTX_TYPE_LEN 82
#define OPC_IMAGE_RELATION_LEN 73
#define OPC_THEME_RELATION_LEN 73
#define OPC_FONT_TABLE_RELATION_LEN 77
#define OPC_STYLES_RELATION_LEN 74
#define OPC_STYLES_WITH_EFFECTS_RELATION_LEN 72
#define OPC_SETTINGS_RELATION_LEN 76
#define OPC_WEB_SETTINGS_RELATION_LEN 79

#endif /* PLUGIN_OPC_H */
