/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : OPC
 #	author : miyako
 #	2013/09/29
 #
 # --------------------------------------------------------------------------------*/

#include "4DPluginAPI.h"

#include "opc_constants.h"

#include "opc_document.h"
#include "opc_resource.h"
#include "opc_relation.h"
#include "opc_utility.h"
