/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : OPC
 #	author : miyako
 #	2017/05/02
 #
 # --------------------------------------------------------------------------------*/

#include "opc_constants.h"
#include "opc_document.h"
#include "opc_resource.h"
#include "opc_relation.h"
#include "opc_utility.h"

// --- OPC Document
void OPC_Get_document_type(sLONG_PTR *pResult, PackagePtr pParams);
void OPC_RESOURCE_TYPE_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void OPC_EXTERNAL_TARGET_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void OPC_EXTENSION_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void OPC_Register_resource_type(sLONG_PTR *pResult, PackagePtr pParams);
void OPC_RELATION_TYPE_LIST(sLONG_PTR *pResult, PackagePtr pParams);

// --- OPC Resource
void OPC_Get_resource(sLONG_PTR *pResult, PackagePtr pParams);
void OPC_RESOURCE_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void OPC_Get_resource_size(sLONG_PTR *pResult, PackagePtr pParams);
void OPC_Delete_resource(sLONG_PTR *pResult, PackagePtr pParams);
void OPC_Set_resource(sLONG_PTR *pResult, PackagePtr pParams);
void OPC_EXTERNAL_RESOURCE_LIST(sLONG_PTR *pResult, PackagePtr pParams);

// --- OPC Relation
void OPC_Create_relation(sLONG_PTR *pResult, PackagePtr pParams);
void OPC_Remove_relation(sLONG_PTR *pResult, PackagePtr pParams);
void OPC_Create_external_relation(sLONG_PTR *pResult, PackagePtr pParams);
void OPC_RELATION_LIST(sLONG_PTR *pResult, PackagePtr pParams);

// --- OPC Constants
void OPC_Document_type(sLONG_PTR *pResult, PackagePtr pParams);
void OPC_Relation_type(sLONG_PTR *pResult, PackagePtr pParams);
