/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : OPC
 #	author : miyako
 #	2013/09/29
 #
 # --------------------------------------------------------------------------------*/

#include "4DPluginAPI.h"

#include "opc_constants.h"

// --- OPC Constants
void OPC_Document_type(sLONG_PTR *pResult, PackagePtr pParams);
void OPC_Relation_type(sLONG_PTR *pResult, PackagePtr pParams);