/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : OPC
 #	author : miyako
 #	2013/09/29
 #
 # --------------------------------------------------------------------------------*/

#include "4DPluginAPI.h"

#ifndef __OPC_CONSTANTS_H__
#define __OPC_CONSTANTS_H__ 1

#include <opc/opc.h>

#include <sstream>

opcPart getPart(opcContainer *container, C_TEXT &path); 
const xmlChar *getRelationType(opcContainer *container, opcPart source, opcRelation rel);
const xmlChar *getRelationPrefixSource(opcContainer *container, opcPart part, opcRelation rel, CUTF8String &prefix, CUTF8String &source);

typedef enum {
	
	OPC_DOCX = 0,
	OPC_XLSX,
	OPC_PPTX
	
}OPC_DOC_TYPE;

typedef enum {
	
	OPC_IMAGE = 0,
	OPC_STYLES,
	OPC_STYLES_WITH_EFFECTS,
	OPC_SETTINGS,
	OPC_WEB_SETTINGS,
	OPC_FONT_TABLE,
	OPC_THEME
	
}OPC_RELATION_TYPE;

#define OPC_ERROR_INVALID_PATH -1
#define OPC_ERROR_INVALID_RESOURCE_ID -2
#define OPC_ERROR_INVALID_RELATION_ID -3
#define OPC_ERROR_INVALID_RELATION_TYPE -4

#define DEFAULT_RELATION_PREFIX (const uint8_t *)"rId"

#define OPC_DOCX_TYPE (const uint8_t *)"application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"
#define OPC_XLSX_TYPE (const uint8_t *)"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"
#define OPC_PPTX_TYPE (const uint8_t *)"application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"

#define OPC_IMAGE_RELATION (const uint8_t *)"http://schemas.openxmlformats.org/officeDocument/2006/relationships/image"
#define OPC_THEME_RELATION (const uint8_t *)"http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme"
#define OPC_FONT_TABLE_RELATION (const uint8_t *)"http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable"
#define OPC_STYLES_RELATION (const uint8_t *)"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles"
#define OPC_STYLES_WITH_EFFECTS_RELATION (const uint8_t *)"http://schemas.microsoft.com/office/2007/relationships/stylesWithEffects"
#define OPC_SETTINGS_RELATION (const uint8_t *)"http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings"
#define OPC_WEB_SETTINGS_RELATION (const uint8_t *)"http://schemas.openxmlformats.org/officeDocument/2006/relationships/webSettings"

#define OPC_DOCX_TYPE_LEN 80
#define OPC_XLSX_TYPE_LEN 74
#define OPC_PPTX_TYPE_LEN 82
#define OPC_IMAGE_RELATION_LEN 73
#define OPC_THEME_RELATION_LEN 73
#define OPC_FONT_TABLE_RELATION_LEN 77
#define OPC_STYLES_RELATION_LEN 74
#define OPC_STYLES_WITH_EFFECTS_RELATION_LEN 72
#define OPC_SETTINGS_RELATION_LEN 76
#define OPC_WEB_SETTINGS_RELATION_LEN 79

#endif